// API types re-exported from domain module for feature layer access
export type {
  TicketStatus,
  TicketLegStatus,
  TicketPriority,
  TicketChannel,
  TicketTaskType,
  TicketWorklogKind,
  TicketDomain,
  Ticket,
  TicketLeg,
  TicketMaterial,
  TicketDetail,
  UnavailableTicket,
  TicketListResponse,
  TicketDetailResponse,
  TicketActionResponse,
  TicketLogEntry as TicketWorklog,
  WorkLogEntryInput,
  NextLegInfo,
  CreateTicketResponse,
  NewLegInput,
  NewTicketInput,
  TicketListFilters,
  WorkSessionMaterialInput,
  WorkSessionPhotoInput,
  WorkSessionSubmitInput,
  TicketPhoto
} from '@/lib/domain/tickets';
