#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=11

# Write the production env to a dedicated, gitignored file — not the dev .env.
cd "$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
ENV_FILE="deploy/kolonios.prod.env"

# emit prints a line flush-left, for paste blocks (e.g. heredoc terminators that
# must start at column 0).
emit() { printf '%s\n' "$1"; }

banner "Kolonios production setup (internal VM)"

# ── 1. Target & prerequisites ─────────────────────────────────────────────
stage "Target & prerequisites"
say "Provisions a Bun + systemd + Caddy + PostgreSQL host and writes $ENV_FILE."
say "Run this from the repo root on your dev machine."
for bin in ssh scp openssl; do
  command -v "$bin" >/dev/null 2>&1 || warn "missing '$bin' — install it before continuing"
done
command -v gh >/dev/null 2>&1 || warn "gh not found — GitHub secrets will be skipped, set them by hand later"

ask APP_URL "App URL users will visit (e.g. https://kolonios.internal):"
ask REPO_URL "Git clone URL of this repo (Enter = local origin):"
ask SSH_USER "SSH user for provisioning (your admin login on the VM):"
ask DEPLOY_HOST "VM IP or hostname:"
ask DEPLOY_USER "Deploy/service user the app runs as on the VM:"
ask DEPLOY_PORT "SSH port:"
ask DEPLOY_PATH "Deploy path on the VM:"
ask DEPLOY_SSH_KEY_PATH "Path to the deploy private key (its public key is authorized):"
ask ADMIN_EMAIL "Email for the first admin account:"

[[ -n "${APP_URL:-}" ]] || { warn "APP_URL is required"; exit 1; }
[[ -n "${DEPLOY_HOST:-}" ]] || { warn "DEPLOY_HOST is required"; exit 1; }
SSH_USER="${SSH_USER:-root}"
DEPLOY_USER="${DEPLOY_USER:-kolonios}"
DEPLOY_PORT="${DEPLOY_PORT:-22}"
DEPLOY_PATH="${DEPLOY_PATH:-/opt/kolonios}"
if [[ -z "${REPO_URL:-}" ]]; then
  REPO_URL="$(git config --get remote.origin.url 2>/dev/null || true)"
fi
[[ -n "${REPO_URL:-}" ]] || warn "REPO_URL empty — clone the repo on the VM manually"

APP_HOST="${APP_URL#*://}"; APP_HOST="${APP_HOST%%/*}"

# Derive the deploy public key so stage 4 can authorize it.
DEPLOY_PUBKEY=""
if [[ -n "${DEPLOY_SSH_KEY_PATH:-}" && -f "${DEPLOY_SSH_KEY_PATH}.pub" ]]; then
  DEPLOY_PUBKEY="$(cat "${DEPLOY_SSH_KEY_PATH}.pub")"
elif [[ -n "${DEPLOY_SSH_KEY_PATH:-}" && -f "${DEPLOY_SSH_KEY_PATH}" ]] && command -v ssh-keygen >/dev/null 2>&1; then
  DEPLOY_PUBKEY="$(ssh-keygen -y -f "$DEPLOY_SSH_KEY_PATH" 2>/dev/null || true)"
fi
[[ -n "$DEPLOY_PUBKEY" ]] || warn "no readable public key — authorize the deploy key by hand in stage 4"

# ── 2. Base OS ────────────────────────────────────────────────────────────
stage "VM: base OS, firewall, tools"
say "SSH in:  ssh -p $DEPLOY_PORT $SSH_USER@$DEPLOY_HOST"
step "Paste these on the VM:"
say "  sudo apt update && sudo apt upgrade -y"
say "  sudo apt install -y ufw git curl ca-certificates rsync ssh"
say "  sudo ufw allow OpenSSH"
say "  sudo ufw allow 80,443/tcp"
say "  sudo ufw --force enable"
note "Internal-only VM behind an existing edge proxy? You can skip opening 80/443."
pause "Base OS done? Press Enter."

# ── 3. Runtime + services ─────────────────────────────────────────────────
stage "VM: install Bun, PostgreSQL, Caddy"
step "Run these on the VM:"
say "  curl -fsSL https://bun.sh/install | bash -s \"bun-v1.4.0\""
say "  sudo install -m 755 \"\$HOME/.bun/bin/bun\" /usr/local/bin/bun"
say "  bun --version    # expect 1.4.0"
say "  sudo apt install -y postgresql postgresql-contrib"
say "  sudo apt install -y debian-keyring debian-archive-keyring apt-transport-https"
say "  curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg"
say "  curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-stable.list"
say "  sudo apt update && sudo apt install -y caddy"
pause "Installed? Press Enter."

# ── 4. Database, service user, repo ───────────────────────────────────────
stage "VM: database, service user, repo"
DB_PASSWORD="$(_existing DB_PASSWORD 2>/dev/null || true)"
[[ -n "$DB_PASSWORD" ]] || DB_PASSWORD="$(openssl rand -hex 32)"
write_env DB_PASSWORD "$DB_PASSWORD"
step "Create the role + database (password generated for you; safe to re-run):"
say "  sudo -u postgres psql -tc \"SELECT 1 FROM pg_roles WHERE rolname='kolonios'\" | grep -q 1 || sudo -u postgres psql -c \"CREATE ROLE kolonios LOGIN PASSWORD '$DB_PASSWORD';\""
say "  sudo -u postgres psql -tc \"SELECT 1 FROM pg_database WHERE datname='kolonios'\" | grep -q 1 || sudo -u postgres psql -c \"CREATE DATABASE kolonios OWNER kolonios;\""
step "Service user (login-capable so CI can deploy), directories, checkout:"
say "  id -u kolonios >/dev/null 2>&1 || sudo useradd --system --home-dir $DEPLOY_PATH --shell /bin/bash kolonios"
say "  sudo mkdir -p $DEPLOY_PATH /etc/kolonios /var/backups/kolonios"
say "  [ -d $DEPLOY_PATH/.git ] || sudo git clone $REPO_URL $DEPLOY_PATH"
say "  sudo chown -R kolonios:kolonios $DEPLOY_PATH"
if [[ -n "$DEPLOY_PUBKEY" ]]; then
  step "Authorize the deploy public key for $DEPLOY_USER:"
  say "  sudo install -d -m 700 -o kolonios -g kolonios $DEPLOY_PATH/.ssh"
  say "  echo '$DEPLOY_PUBKEY' | sudo tee $DEPLOY_PATH/.ssh/authorized_keys"
  say "  sudo chown kolonios:kolonios $DEPLOY_PATH/.ssh/authorized_keys && sudo chmod 600 $DEPLOY_PATH/.ssh/authorized_keys"
else
  note "Authorize your deploy public key in $DEPLOY_PATH/.ssh/authorized_keys by hand."
fi
note "Private repo? Use a deploy key or token in the clone URL."
pause "Done? Press Enter."

# ── 5. App secrets → env file ─────────────────────────────────────────────
stage "App secrets → $(basename "$ENV_FILE")"
BETTER_AUTH_SECRET="$(_existing BETTER_AUTH_SECRET 2>/dev/null || true)"
[[ -n "$BETTER_AUTH_SECRET" ]] || BETTER_AUTH_SECRET="$(openssl rand -hex 32)"
STORAGE_ENCRYPTION_KEY="$(_existing STORAGE_ENCRYPTION_KEY 2>/dev/null || true)"
[[ -n "$STORAGE_ENCRYPTION_KEY" ]] || STORAGE_ENCRYPTION_KEY="$(openssl rand -hex 32)"
write_env NODE_ENV production
write_env HOST 127.0.0.1
write_env PORT 3000
write_env LOG_LEVEL info
write_env DATABASE_URL "postgres://kolonios:$DB_PASSWORD@127.0.0.1:5432/kolonios"
write_env BETTER_AUTH_SECRET "$BETTER_AUTH_SECRET"
write_env BETTER_AUTH_URL "$APP_URL"
write_env BETTER_AUTH_TRUSTED_ORIGINS "$APP_URL"
write_env STORAGE_ENCRYPTION_KEY "$STORAGE_ENCRYPTION_KEY"
write_env VITE_MAP_TILE_URL "https://tile.openstreetmap.org/{z}/{x}/{y}.png"
write_env RATE_LIMIT_MAX 150
write_env RATE_LIMIT_WINDOW_MS 60000
write_env AUTH_RATE_LIMIT_WINDOW 60
write_env AUTH_RATE_LIMIT_MAX 150
write_env AUTH_RATE_LIMIT_MAX_SIGNIN 8
warn "Back up STORAGE_ENCRYPTION_KEY elsewhere — without it, saved S3 credentials can't be decrypted."

# ── 6. Sentry (optional) ──────────────────────────────────────────────────
stage "Sentry (optional)"
if confirm "Configure Sentry error tracking?"; then
  open_url "https://sentry.io"
  say "Create/select a project and copy its DSN."
  ask SENTRY_DSN "Paste the DSN:"
  write_env SENTRY_DSN "$SENTRY_DSN"
  write_env SENTRY_TRACES_SAMPLE_RATE 0.1
else
  note "Skipping Sentry."
fi

# ── 7. Install env + units on the VM ──────────────────────────────────────
stage "Install env, systemd unit, Caddy"
step "Copy the env file to the VM:"
say "  scp -P $DEPLOY_PORT $ENV_FILE $SSH_USER@$DEPLOY_HOST:/tmp/kolonios.env"
say "  ssh -p $DEPLOY_PORT $SSH_USER@$DEPLOY_HOST \"sudo install -m 640 -o root -g kolonios /tmp/kolonios.env /etc/kolonios/kolonios.env && rm /tmp/kolonios.env\""
note "640 (not 600): the kolonios service user must read it to run deploy.sh."
step "Let the service user restart the app without a password:"
say "  echo 'kolonios ALL=(root) NOPASSWD: /usr/bin/systemctl restart kolonios' | sudo tee /etc/sudoers.d/kolonios-restart"
step "Install the systemd unit:"
say "  sudo cp $DEPLOY_PATH/deploy/kolonios.service /etc/systemd/system/kolonios.service"
say "  sudo systemctl daemon-reload && sudo systemctl enable kolonios"
step "Install Caddy:"
if confirm "Does this VM terminate TLS for a public domain (Caddy auto-HTTPS)?"; then
  say "  sudo cp $DEPLOY_PATH/deploy/Caddyfile /etc/caddy/Caddyfile"
else
  say "  sudo cp $DEPLOY_PATH/deploy/Caddyfile.internal /etc/caddy/Caddyfile"
  note "Self-signed: browsers warn until the internal CA is trusted."
fi
say "  sudo mkdir -p /etc/systemd/system/caddy.service.d"
say "  printf '[Service]\\nEnvironmentFile=/etc/default/caddy\\n' | sudo tee /etc/systemd/system/caddy.service.d/kolonios-env.conf"
say "  echo 'DOMAIN=$APP_HOST' | sudo tee /etc/default/caddy"
say "  sudo systemctl daemon-reload && sudo systemctl restart caddy"
note "The package's caddy.service doesn't read /etc/default/caddy; the drop-in is what supplies DOMAIN."
note "For auto-HTTPS, DNS for $APP_HOST must point at $DEPLOY_HOST."
pause "Installed? Press Enter."

# ── 8. First deploy + health ──────────────────────────────────────────────
stage "First deploy & health check"
step "On the VM:"
say "  cd $DEPLOY_PATH && sudo -u kolonios APP_DIR=$DEPLOY_PATH bash deploy/deploy.sh"
note "deploy.sh installs, builds, migrates --no-seed, restarts, then polls /api/v1/health."
step "From your machine:"
say "  curl -k $APP_URL/api/v1/health    # -k tolerates the self-signed cert"
pause "Health returned {\"status\":\"ok\"}? Press Enter."

# ── 9. First admin account ────────────────────────────────────────────────
stage "First admin account"
step "1) Open the sign-in page and register with $ADMIN_EMAIL:"
open_url "$APP_URL/auth/v2/sign-in"
ADMIN_EMAIL_SQL="${ADMIN_EMAIL//\'/\'\'}"
step "2) On the VM, grant that account full access (paste the whole block):"
say "  set -a; source /etc/kolonios/kolonios.env; set +a"
emit ""
emit "psql \"\$DATABASE_URL\" <<'SQL'"
emit "INSERT INTO role_groups (id,name,description,permissions,is_admin)"
emit "VALUES ('zzzrg-admin','Administrator','Full system access','{}'::jsonb,true)"
emit "ON CONFLICT (id) DO NOTHING;"
emit "INSERT INTO user_role_groups (user_id,role_group_id)"
emit "SELECT id,'zzzrg-admin' FROM \"user\" WHERE email='$ADMIN_EMAIL_SQL'"
emit "ON CONFLICT (user_id) DO NOTHING;"
emit "UPDATE \"user\" SET role='admin' WHERE email='$ADMIN_EMAIL_SQL';"
emit "SQL"
emit ""
pause "Admin can see the full dashboard? Press Enter."

# ── 10. GitHub secrets for CD ─────────────────────────────────────────────
stage "GitHub secrets for CI deploy"
say "These let .github/workflows/deploy.yml ship green CI to the VM."
set_secret DEPLOY_HOST "$DEPLOY_HOST"
set_secret DEPLOY_USER "$DEPLOY_USER"
set_secret DEPLOY_PORT "$DEPLOY_PORT"
set_secret DEPLOY_PATH "$DEPLOY_PATH"
if [[ -n "${DEPLOY_SSH_KEY_PATH:-}" && -f "$DEPLOY_SSH_KEY_PATH" ]]; then
  set_secret DEPLOY_SSH_KEY "$(cat "$DEPLOY_SSH_KEY_PATH")"
  note "Public key authorized at $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH/.ssh/authorized_keys."
else
  SKIPPED+=("GitHub secret DEPLOY_SSH_KEY (authorize the deploy public key on the VM, then set it)")
  warn "no readable key at that path — set DEPLOY_SSH_KEY by hand"
fi

# ── 11. Backups & object storage ──────────────────────────────────────────
stage "Backups & object storage"
step "Daily database backup (on the VM):"
say "  sudo crontab -u kolonios -e"
say "  0 3 * * * ENV_FILE=/etc/kolonios/kolonios.env $DEPLOY_PATH/deploy/backup-postgres.sh"
note "Run a test restore before you rely on it."
step "Object storage: create an S3 bucket (AWS S3 / Cloudflare R2 / DO Spaces),"
say "then enter its credentials in the app at Admin → Storage Settings."
say "They are encrypted with STORAGE_ENCRYPTION_KEY from $(basename "$ENV_FILE")."

finish
